spring:
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/hellomall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开启二级缓存
    cache-enabled: true
  type-aliases-package: com.dz.pojo
  mapper-locations: classpath:/mapper/*.xml


